name: Scala CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.12.20, 2.13.16, 3.3.6]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Check formatting
        run: sbt -v "scalafixAll --check; scalafmtCheck"
      - name: Run tests
        run: sbt -v "++${{ matrix.scala-version }} clean; test;"
